### ISSUE TITLE
Wrong bubble width for non-latin text

### ISSUE THREAD

**Issue by smeagol74** [xyproto/botsay#1]
When using some non latin chars it's wrongly calculates the width of the bubble. The issue become critical for long texts with multiline. It breaks the picture totally. Looks like when it calculates the bubble width, all non latin chars are calculated twice.

**How to reproduce:**

Just execute something like `botsay 'Привет'` 

**What you see:**

```  
 .--------------.
 | Привет       |
 '--------------'
```

**Expected behaviour:**

```
 .--------.
 | Привет |
 '--------'
```

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into this.

**Comment by smeagol74** [comment]
Thank you. The issue is in the `len` function you are using. It returns bytes count for unicode strings, not the runes as expected.
