### ISSUE TITLE
Botsay won't read input from stdin

### ISSUE THREAD

**Issue by dfimium499** [xyproto/botsay#3]
Right now it appears that unlike cowsay, botsay does not take any input from stdin when no message is provided, which could be a nice feature to add.

Here's an example of current behaviour and a quick comparison with cowsay:
![sample_botsay](https://github.com/user-attachments/assets/a4ecbf3e-941e-4d44-9b72-945f18c0e863)

Notice that my botsay version was installed from AUR. I've checked the repository and it looks like the latest version, but perhaps there's some mismatch I'm not aware of.

**Comment by dfimium499** [comment]
By the way, could I get this assigned to me, please? I'm working on it and it shouldn't take too long, just a quick fix.

**Comment by xyproto** [comment]
Closed with #4
