### ISSUE TITLE
README inaccuracies

### ISSUE THREAD

**Issue by dfimium499** [xyproto/botsay#5]
Current README lacks description of -o flag and examples are inaccurate. For instance:

`botsay -- $(botsay;botsay;botsay)`

will not work as expected, as botsay will wait for stdin input. -o flag is to be set to prevent this.

`date --iso-8601 | botsay -`

will not display the date but instead '-', because the single character is parsed as a message. I'm not entirely sure how this got here, as this example is older than pipe support, but either way the explanation is inaccurate.

Besides, I'd suggest changing examples where evaluation is used by pipes, as it is generally a better practice so as to avoid unexpected behaviour caused by badly parsed command output.

Here's a screenshot with the actual behaviour of botsay's current version:
![inacc_bh](https://github.com/user-attachments/assets/6f0d2c2a-f701-462e-8d66-02a1c50fceeb)

**Comment by dfimium499** [comment]
It shouldn't take me more than 5 minutes

**Comment by dfimium499** [comment]
PR posted, can't link it because of privileges

**Comment by xyproto** [comment]
Closed by #6 

Submitting PRs without issues are also fine, btw.🙂

Have an excellent day!
